#!/usr/bin/env sh

case $1 in
  "api")
    docker-compose down -v && docker-compose up -d
    kill "$(lsof -t -i:9000)" || kill "$(lsof -t -i:9229)" || true
    kill $(ps aux | grep nx | awk '{print $2}') || true
    echo 'Waiting for Postgres to be ready...' && sleep 5
    echo 'Spinning up Fastify in the background...' && nohup pnpm dev > .api.logs &
    pnpm migrate-latest
    echo "The database and API server have been refreshed!"
    ;;
  "kill-api")
    kill "$(lsof -t -i:9000)" || kill "$(lsof -t -i:9229)" || true
    kill $(ps aux | grep nx | awk '{print $2}') || true
    ;;
  "refresh-api")
    kill "$(lsof -t -i:9000)" || kill "$(lsof -t -i:9229)" || true
    kill $(ps aux | grep nx | awk '{print $2}') || true
    echo 'Spinning up Fastify in the background...' && nohup pnpm dev > .api.logs &
    ;;
  *)
    echo "Usage: $0 { api }"
    ;;
esac
